"""Added total_equity column

Revision ID: 3b4723ab8718
Revises: 8b91b5524904
Create Date: 2025-02-08 20:25:58.054608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4723ab8718'
down_revision = '8b91b5524904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('is_open', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('daily_drawdown', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('last_trade_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('is_suspended', sa.Boolean(), nullable=True))
    op.alter_column('user', 'total_equity',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'total_equity',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('user', 'is_suspended')
    op.drop_column('user', 'last_trade_date')
    op.drop_column('user', 'daily_drawdown')
    op.drop_column('trade', 'is_open')
    # ### end Alembic commands ###
